#!/usr/bin/env python3
"""
Vocabulary-V2 Project Starter
Generated by fix_all_projects.py
"""

import sys
import os
from pathlib import Path

# 프로젝트 설정
PROJECT_NAME = "vocabulary-v2"
PROJECT_TYPE = "react"
PORT_RANGE = (3100, 3109)
DEFAULT_PORT = 3100

# template 디렉토리 경로 설정
template_paths = [
    Path.home() / "projects" / "template",
    Path(__file__).parent.parent / "template",
    Path(__file__).parent / "template",
]

# project_manager 경로 찾기
for template_dir in template_paths:
    if template_dir.exists() and (template_dir / "project_manager").exists():
        sys.path.insert(0, str(template_dir))
        break
else:
    print("❌ Error: project_manager not found in any of these locations:")
    for path in template_paths:
        print(f"   - {path}")
    print("\n💡 Solutions:")
    print("   1. Make sure the template directory exists at ~/projects/template")
    print("   2. Or run: python ~/projects/template/install_project_manager.py .")
    sys.exit(1)

try:
    from project_manager import ProjectAPI
except ImportError as e:
    print(f"❌ Error importing project_manager: {e}")
    print("💡 Make sure all dependencies are installed")
    sys.exit(1)


def main():
    """메인 함수"""
    print(f"🚀 Starting {PROJECT_NAME}...")
    print(f"📋 Type: {PROJECT_TYPE}")
    print(f"🔌 Port Range: {PORT_RANGE[0]}-{PORT_RANGE[1]}")
    print(f"🎯 Default Port: {DEFAULT_PORT}")
    print("=" * 50)
    
    # API 인스턴스 생성
    api = ProjectAPI(
        name=PROJECT_NAME,
        project_type=PROJECT_TYPE,
        port_range=PORT_RANGE,
        working_directory=os.getcwd(),
        enable_health_checks=True
    )
    
    try:
        # 프로젝트 시작
        print("⏳ Starting project...")
        result = api.start(port=DEFAULT_PORT)
        
        if result.success:
            print(f"\n✅ {PROJECT_NAME} started successfully!")
            
            # 결과 데이터에서 정보 추출
            if hasattr(result, 'data') and result.data:
                if isinstance(result.data, dict):
                    print(f"🌐 URL: {result.data.get('url', 'N/A')}")
                    print(f"🔌 Port: {result.data.get('port', 'N/A')}")
                    print(f"📊 PID: {result.data.get('pid', 'N/A')}")
                else:
                    print(f"🌐 URL: {getattr(result.data, 'url', 'N/A')}")
                    print(f"🔌 Port: {getattr(result.data, 'port', 'N/A')}")
                    print(f"📊 PID: {getattr(result.data, 'pid', 'N/A')}")
            
            print("\n" + "=" * 50)
            print("📱 Project is running!")
            print("🛑 Press Ctrl+C to stop...")
            print("=" * 50)
            
            # 실행 유지
            try:
                while True:
                    import time
                    time.sleep(1)
            except KeyboardInterrupt:
                print("\n\n🛑 Interrupt received, stopping project...")
        
        else:
            print(f"\n❌ Failed to start {PROJECT_NAME}!")
            print(f"💬 Error: {result.message}")
            
            # 에러 메시지에 따른 도움말
            error_msg = str(result.message).lower()
            if "command" in error_msg or "npm" in error_msg:
                print("\n🔍 Troubleshooting tips:")
                print("  • Make sure you have npm installed")
                print("  • Run 'npm install' in your project directory")
                print("  • Check if package.json exists")
                print("  • Verify your start command in package.json")
            elif "port" in error_msg:
                print("\n🔍 Port troubleshooting:")
                print("  • Check if another process is using the port")
                print(f"  • Try: lsof -i :{DEFAULT_PORT}")
                print("  • The system will try other ports in the range automatically")
            
            return False
    
    except Exception as e:
        print(f"\n💥 Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        return False
    
    finally:
        # 정리 작업
        print("\n🧹 Cleaning up...")
        try:
            stop_result = api.stop()
            if stop_result.success:
                print("✅ Project stopped successfully!")
            else:
                print(f"⚠️ Warning during stop: {stop_result.message}")
        except Exception as e:
            print(f"⚠️ Error during cleanup: {e}")
    
    return True


def check_status():
    """프로젝트 상태 확인"""
    try:
        api = ProjectAPI(
            name=PROJECT_NAME,
            project_type=PROJECT_TYPE,
            port_range=PORT_RANGE,
            working_directory=os.getcwd()
        )
        status = api.status()
        
        print(f"📊 {PROJECT_NAME} Status")
        print("=" * 40)
        print(f"Status: {status.project_status}")
        print(f"Port: {status.port or 'N/A'}")
        print(f"URL: {status.url or 'N/A'}")
        print(f"Health: {status.health_status or 'N/A'}")
        print(f"PID: {status.pid or 'N/A'}")
        
        if hasattr(status, 'uptime_seconds') and status.uptime_seconds:
            hours = int(status.uptime_seconds // 3600)
            minutes = int((status.uptime_seconds % 3600) // 60)
            seconds = int(status.uptime_seconds % 60)
            print(f"Uptime: {hours}h {minutes}m {seconds}s")
    
    except Exception as e:
        print(f"❌ Error checking status: {e}")


if __name__ == "__main__":
    # 명령줄 옵션 처리
    if len(sys.argv) > 1:
        if sys.argv[1] == "status":
            check_status()
            sys.exit(0)
        elif sys.argv[1] == "help":
            print("Usage:")
            print("  python start.py        # Start the project")
            print("  python start.py status # Check project status")
            print("  python start.py help   # Show this help")
            sys.exit(0)
    
    # 메인 함수 실행
    success = main()
    sys.exit(0 if success else 1)
